### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by hannesvdvreken** [madewithlove/why-cant-we-have-nice-things#1]
![screen shot 2015-10-26 at 09 55 48](https://cloud.githubusercontent.com/assets/1410358/10724837/c5c1f350-7bc7-11e5-9966-72cc5b371f6f.png)
![screen shot 2015-10-26 at 09 56 00](https://cloud.githubusercontent.com/assets/1410358/10724838/c5c418d8-7bc7-11e5-9a4b-d9fc369858fa.png)

**Comment by Anahkiasen** [comment]
Missing an `i` regex flag [here](https://github.com/madewithlove/why-cant-we-have-nice-things/blob/master/resources/assets/js/TablesHandler.js#L36)
