### ISSUE TITLE
My profile seems wrong

### ISSUE THREAD

**Issue by marcioAlmada** [madewithlove/why-cant-we-have-nice-things#17]
http://why-cant-we-have-nice-things.mwl.be/users/206

I made 3 RFCs, 2 passed one was solely rejected. The profile shows only one accepted RFC. Not really a complain, but maybe this means there is a problem while parsing the RFCs? I've noticed other profiles are not 100% complete too.

Anyway, this is a wonderful tool. Nice job!

**Comment by Anahkiasen** [comment]
Yeah this is all heavily work in progress, the app still has some issues uniformizing user profiles between the votes, the RFC authors sections and the mailing list and stuff. There's an issue opened for that actually, will need to look into it

**Comment by Anahkiasen** [comment]
Yes that's what it is. The rest of your RFCs are under `marcio@php.net` http://why-cant-we-have-nice-things.mwl.be/users/13

The app isn't public yet so, will be fixed before public release. Lots of features missing or stuff broken at the moment, I'd avoid posting the link anywhere :D

**Comment by marcioAlmada** [comment]
Cool. It doesn't help much that some of the RFCs have no email address or use different email addresses. E.g: I started using gmail and later got a php.net account (this happens to many, apparently).
:+1:

**Comment by Anahkiasen** [comment]
@marcioAlmada Can you link to your three RFCs?

**Comment by marcioAlmada** [comment]
Sure:
- https://wiki.php.net/rfc/context_sensitive_lexer
- https://wiki.php.net/rfc/strict_argcount
- https://wiki.php.net/rfc/group_use_declarations

Others are still in draft. Also, these users have an incomplete profile too:

- http://why-cant-we-have-nice-things.mwl.be/users/1
- http://why-cant-we-have-nice-things.mwl.be/users/2

They are probably 2 of the most active contributors so I'm pretty sure they may have more than 12 RFCs each one. Hope that helps to debug :)

**Comment by Anahkiasen** [comment]
Ok I've made the extractor a bit better at handling the million formats of the Author field and made the users infos unifier a bit smarter. Seems a bit better from what I see:

http://why-cant-we-have-nice-things.mwl.be/users/1
http://why-cant-we-have-nice-things.mwl.be/users/2
http://why-cant-we-have-nice-things.mwl.be/users/13

Do you see any other major incorrect user informations on the current test version?

**Comment by marcioAlmada** [comment]
Not now. But I'll keep looking. Good Job!

**Comment by marcioAlmada** [comment]
PS: Another suggestion would be to use gender neutral pronouns as much as possible. For example, this profile is erroneously identified as "he" http://why-cant-we-have-nice-things.mwl.be/users/57. You could just save yourself some work by avoiding being gender specific in the first place.

**Comment by Anahkiasen** [comment]
[way ahead of you](https://github.com/madewithlove/why-cant-we-have-nice-things/commit/8c7b2262a6ef3af87377f18bc0e60de1fb98a2b8) :D

**Comment by marcioAlmada** [comment]
:wink:
