### ISSUE TITLE
Add debugbar in local environments

### ISSUE THREAD

**Issue by Anahkiasen** [madewithlove/why-cant-we-have-nice-things#40]

**Comment by Anahkiasen** [comment]
Seems it doesn't work well with illuminate/database so not worth it

**Comment by hannesvdvreken** [comment]
Why not? Maybe you can leverage https://github.com/barryvdh/laravel-debugbar/blob/master/src/DataCollector/QueryCollector.php?

**Comment by Anahkiasen** [comment]
Yeah I thought about it but it hurts me to have to include all of laravel-debugbar just for one class. Plus it's a pain to setup the assets and stuff, made it work at lunch but, just to check on queries from time to time, it's not worth the extra code complexity everywhere

**Comment by hannesvdvreken** [comment]
I included `league/uri` once for ONE class. That package has hundreds of classes.

**Comment by Anahkiasen** [comment]
ಠ_ಠ

**Comment by Anahkiasen** [comment]
Done
