### ISSUE TITLE
Wrong RFC state

### ISSUE THREAD

**Issue by kelunik** [madewithlove/why-cant-we-have-nice-things#79]
http://why-cant-we-have-nice-things.mwl.be/events shows https://wiki.php.net/rfc/invalid_strings_in_arithmetic as implemented, but the vote was canceled and it was put under discussion again.

**Comment by Anahkiasen** [comment]
I'm guessing the code is giving the votes priority over the status at some point, cause from a votes standpoint it would have been implemented. Will look into it.
