### ISSUE TITLE
Company name gets stuck

### ISSUE THREAD

**Issue by realityking** [madewithlove/why-cant-we-have-nice-things#80]
I just noticed that the page about me (http://why-cant-we-have-nice-things.mwl.be/requests/deprecate-mb-ereg-replace-eval-option) still indicates my old employer despite updating it on GitHub a while ago. It's kinda awkward that my actions may be associated with a company that has no connection to me anymore.

Maybe periodically (once a month?) the data should be refetched from GitHub?

**Comment by Anahkiasen** [comment]
The issue is Github's rate limit is _very_ aggressive, I can't even fetch user metadata all at once, it's spread over cron jobs until all metadata is fetched. I'm gonna add something so that it starts refreshing it once it's done one complete pass at least, so it refreshes it from time to time.

**Comment by realityking** [comment]
Awesome! Thank you :)
