### ISSUE TITLE
Missing RFCs

### ISSUE THREAD

**Issue by kelunik** [madewithlove/why-cant-we-have-nice-things#93]
https://why-cant-we-have-nice-things.mwl.be/users/kelunik doesn't show https://wiki.php.net/rfc/parameter-no-type-variance and https://wiki.php.net/rfc/improved-tls-constants, maybe others and I don't get why. Could you help how they're connected?

**Comment by kelunik** [comment]
Guess it just hasn't updated its data.

**Comment by Anahkiasen** [comment]
Tracking in #105
